project:
  output-dir: docs
  render:
    - cv-academic.qmd
    - cv-academic-es.qmd
    - cv-industry.qmd
    - cv-industry-es.qmd
    - index.qmd

execute:
  echo: false
  warning: false
  message: false

format:
  html:
    toc: false
    page-layout: article
    css: assets/styles.css
    theme: none
    embed-resources: true
    html-math-method: plain
    grid:
      body-width: 800px
  typst:
    template-partials:
      - templates/typst-show.typ
      - templates/typst-template.typ
  docx:
    reference-doc: templates/reference.docx
    highlight-style: none
